import { ObjectsType } from "@/types/object";

export const ObjectList: ObjectsType[] = [
  { id: "person", src: "/palette/person.png", alt: "Person" },
  { id: "man", src: "/palette/man.png", alt: "Man" },
  { id: "woman", src: "/palette/woman.png", alt: "Woman" },
  { id: "humanface", src: "/palette/humanface.png", alt: "Human face" },
  { id: "musical", src: "/palette/musical.png", alt: "Music" },
  { id: "sports", src: "/palette/sports.png", alt: "Sport" },
  { id: "skateboard", src: "/palette/skateboard.png", alt: "Skateboard" },
  { id: "glasses", src: "/palette/glasses.png", alt: "Glasses" },
  { id: "bicycle", src: "/palette/bicycle.png", alt: "Bicycle" },
  { id: "motorcycle", src: "/palette/motorcycle.png", alt: "Motorcycle" },
  { id: "car", src: "/palette/car.png", alt: "Car" },
  { id: "truck", src: "/palette/truck.png", alt: "Truck" },
  { id: "boat", src: "/palette/boat.png", alt: "Boat" },
  { id: "parachute", src: "/palette/parachute.png", alt: "Parachute" },
  { id: "airplane", src: "/palette/airplane.png", alt: "Air plane" },
  { id: "bench", src: "/palette/bench.png", alt: "Bench" },
  { id: "chair", src: "/palette/chair.png", alt: "Chair" },
  { id: "couch", src: "/palette/sofa.png", alt: "Couch" },
  { id: "building", src: "/palette/building.png", alt: "Building" },
  { id: "umbrella", src: "/palette/umbrella.png", alt: "Umbrella" },
  { id: "wineglass", src: "/palette/wineglass.png", alt: "Wine glass" },
  { id: "cup", src: "/palette/cup.png", alt: "Cup" },
  { id: "dessert", src: "/palette/dessert.png", alt: "Dessert" },
  { id: "cellphone", src: "/palette/cellphone.png", alt: "Cellphone" },
  { id: "television", src: "/palette/television.png", alt: "Television" },
  { id: "laptop", src: "/palette/laptop.png", alt: "Laptop" },
  { id: "book", src: "/palette/book.png", alt: "Book" },
  { id: "cat", src: "/palette/cat.png", alt: "Cat" },
  { id: "dog", src: "/palette/dog.png", alt: "Dog" },
  { id: "horse", src: "/palette/horse.png", alt: "Horse" },
  { id: "bird", src: "/palette/bird.png", alt: "Bird" },
  { id: "flower", src: "/palette/flower.png", alt: "Flower" },
  { id: "tree", src: "/palette/tree.png", alt: "Tree" },
];
